### ISSUE TITLE
To-do admin

### ISSUE THREAD

**Issue by obrunodev** [PyxelSolucoes/club#1]
# Tarefas para usuário admin
### Usuário poderá gerenciar produtos e pedidos/comandas.

- [x] Login admin
  - [x] Tela de login
  - [x] Hash senha com bcrypt
  - [x] Config session
  - [x] Login de admin
---
- [x] Tela de menu
- [ ] Gerar comandas
---
- [ ] Produtos
  - [x] Tela de cadastro de produtos
  - [x] Rota de cadastro
  - [x] Rota de exclusão
  - [ ] Tela edit
  - [ ] Rota de edição
  - [x] Listar produtos
---
- [ ] Finalizar pedido
  - [ ] Excluir comanda
  - [ ] Excluir pedidos relacionados a comanda removida
